working on disocvery service (needs to be generalized) started working on general docker get functions for remote api

diff --git a/setup/files/dnas.j2 b/setup/files/dnas.j2
--- a/setup/files/dnas.j2
+++ b/setup/files/dnas.j2
@@ -2,8 +2,38 @@
 # this file contains environment variables for the different docker init files
 #
 
-# the file is loaded by unit files from systemd
+# variables for systemd files
+plex_port={{plex_port}}
+sabnzbd_port={{sabnzbd_port}}
+sickbeard_port={{sickbeard_port}}
+couchpotato_port={{couchpotato_port}}
+
+
+
+{% raw %}
 
 etcd_ip=`ip add show dev docker0 | grep inet | sed -e 's/^[ \t]*//' | cut -d" " -f2 | sed -e 's/\///'`
+rssdler_daemon=`/usr/bin/docker inspect -f '{{index .Volumes "/var/lib/rssdler" }}' rssdler`/workingdir/daemon.info
 
-rssdler_daemon=`/usr/bin/docker inspect -f '\{\{index .Volumes "/var/lib/rssdler" \}\}' rssdler`/workingdir/daemon.info
+
+
+
+arr=($(echo -e "GET /images/json HTTP/1.1\r\n" | socat unix-connect:/var/run/docker.sock STDIO | sed '/^\s*$/d'))
+
+
+
+
+function get_container_ip {
+
+  ip=`docker inspect --format='{{.NetworkSettings.IPAddress}}' $1`
+
+  if [ $? -ne 0 ]; then
+    >&2 echo "could not retrieve ip from container '$1'"
+    exit 1
+  fi
+
+  echo $ip
+}
+
+{% endraw %}
+
